In [1]:
import numpy as np

In [2]:
aar1 = ([1,2,3,4,5,6,7])
aar11 = ([0,1,2,3,4,5,6,7])
print(np.all(aar1))
print(np.all(aar11))

True
False


In [3]:
aar2 = ([1,2,3,4,5,6,7])
aar21 = ([0,1,2,3,4,5,6,7])
print(np.any(aar2))
print(np.any(aar21))

True
True


In [4]:
aar3 = ([10.0001,1,2,3,4,5,6,7])
aar31 = ([10,1,2,3,4,5,6,7])

print(np.equal(aar3, aar31))
print(np.allclose(aar3, aar31))

[False  True  True  True  True  True  True  True]
True


In [5]:
aar4 = np.arange(30)
aar4[0:10] = 0
aar4[10:20] = 1
aar4[20:] = 5
aar4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5])

In [6]:
arr5 = np.arange(30,71)
arr5

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [7]:
aar6 = np.identity(3)
aar6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
aar7 = np.random.rand(1)
aar7

array([0.84793465])

In [9]:
aar8 = np.random.normal(size = 15)
aar8

array([-0.27270575,  0.46009621, -0.19082394, -0.73580435, -0.55757141,
        3.80518544,  1.1243275 , -1.25237844,  0.32001021, -0.2638559 ,
       -1.3780148 ,  0.27465159,  0.70649193, -0.34912969, -0.24402772])

In [10]:
aar9 = np.arange(15,56)
aar9[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [11]:
aar10 = np.random.randint(0,10,5)
aar10

array([8, 6, 6, 5, 2])

In [12]:
aar110 = np.zeros((8,8))
aar111 = np.ones(8)
aar112 = np.vstack((aar111, aar110))
aar113 = np.vstack((aar112, aar111))
aar114 = np.ones(10)
aar115 = aar114.reshape(10,1)
aar116 = np.hstack((aar115, aar113))
aar117 = np.hstack((aar116, aar115))
aar11 =aar117
print(aar11.shape)
aar11

(10, 10)


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
aar12 = np.diag([1, 2, 3, 4, 5])
aar12

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [14]:
aar13 = np.zeros((4,4))
aar13[::2,1::2]=1
aar13[1::2,::2]=1
aar13

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [15]:
import os
aar140 = np.arange(5)
aar141 = np.arange(6,10)
np.savez("npz.npz", x=aar140, y=aar141)
with np.load('npz.npz') as data:
    new140 = data["x"]
    new141 = data["y"]
print(new140, new141)

[0 1 2 3 4] [6 7 8 9]


In [16]:
aar15 = np.random.rand(40)
aar15

array([0.49745691, 0.03997093, 0.71008653, 0.67945139, 0.84610169,
       0.70439676, 0.52147775, 0.06334343, 0.68057041, 0.0650754 ,
       0.22026362, 0.69471139, 0.50158267, 0.82173968, 0.90712416,
       0.28273057, 0.35170499, 0.68994585, 0.57774541, 0.65463029,
       0.34335159, 0.13823734, 0.09689591, 0.06675072, 0.46682351,
       0.53418813, 0.22765754, 0.12602118, 0.57045247, 0.41143571,
       0.69148033, 0.91592452, 0.20624318, 0.2742809 , 0.44808079,
       0.56172069, 0.18275671, 0.97734257, 0.54701052, 0.90081584])

In [17]:
aar16 = aar9
aar16[aar16>25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55])